# Generated by Django 3.0.3 on 2020-02-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='tituloPost',
        ),
    ]
